### ISSUE TITLE
License for Model Weights

### ISSUE THREAD

**Issue by jamesdolezal** [Boehringer-Ingelheim/stain-transfer#4]
Thank you for releasing the code and pretrained model weights for your stain normalization implementations! This is a great resource for folks looking for a one-stop shop for a variety of normalization techniques.

I'd like to be able to implement one of your pretrained models in another repository. This repository has a BSD-2-Clause license, but the [OSF repository](https://osf.io/byf27/) containing the model pretrained weights does not currently have a license listed. While I would assume the license is probably the same, could you add a license to that repository as well, to ensure others can use and distribute the weights you have provided?

Thanks for your consideration and for your tremendous efforts!

**Comment by igsing** [comment]
BSD 2-Clause license was added to OSF repository (models and data)
